<a href="https://colab.research.google.com/github/ayan6943/python-lib-notebooks/blob/main/Unit_1_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr2 = np.random.randint(10, 50, (3, 4))  # 3x4 array with values between 10 and 49
print(arr2)


[[23 28 29 30]
 [39 25 29 11]
 [22 18 24 19]]


In [ ]:
arr1 = np.random.randint(10, 50,10)  # 3x4 array with values between 10 and 49
print(arr1)


[22 17 29 12 14 17 49 16 28 16]


In [ ]:
#print(arr1[::2])
print(arr2[1,2]) # indexing in matrix also starts with 0 only
print(arr2[:,::3]) # Selecting only first and last columns

29
[[23 30]
 [39 11]
 [22 19]]


**Array Slicing: Accessing Subarrays**
Just as we can use square brackets to access individual array elements, we can also use them to access subarrays with the slice notation, marked by the colon (:) character. The NumPy slicing syntax follows that of the standard Python list; to access a slice of an array x, use this:

x[start:stop:step]
If any of these are unspecified, they default to the values start=0, stop=<size of dimension>, step=1. Let's look at some examples of accessing subarrays in one dimension and in multiple dimensions.

In [ ]:
# Sub Array
sub=arr2[1:,2:]
print(sub) #Unlike Python list slices, NumPy array slices are returned as views rather than copies of the array data.
#Despite the nice features of array views, it is sometimes useful to instead explicitly copy the data within an array or a subarray.
#This can be most easily done with the copy method
sub1=arr2[1:,2:].copy()
print(sub1)
sub1[1,1]=10
print(sub1)
sub[1,1]=15
print(arr2)

[[29 11]
 [24 19]]
[[29 11]
 [24 19]]
[[29 11]
 [24 10]]
[[23 28 29 30]
 [39 25 29 11]
 [22 18 24 15]]


In [ ]:
rearr=np.arange(10).reshape(2,5)
print(rearr)
# dimentions(x,y)   x*y=total elements

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
vec=np.array([1,4,7,8,55,7,8,5,95,54,1])
col_vector = vec[:, np.newaxis]
print(col_vector.shape)  # (3, 1) → 2D column vector
print(col_vector)


(11, 1)
[[ 1]
 [ 4]
 [ 7]
 [ 8]
 [55]
 [ 7]
 [ 8]
 [ 5]
 [95]
 [54]
 [ 1]]


In [ ]:
# flatten 2D array to 1D
array1 = np.array([[1, 3], [5, 7], [9, 11]])
result1 = np.reshape(array1, -1)
print("Flattened 2D array:", result1)

Flattened 2D array: [ 1  3  5  7  9 11]


# **Universal Functions (Ufuncs)**

In [ ]:
#consists of standard +-*/**
uarr=np.arange(10)
print(uarr*1+5)


[ 5  6  7  8  9 10 11 12 13 14]


The following table lists the arithmetic operators implemented in NumPy:

Operator	Equivalent ufunc	Description
+	np.add	Addition (e.g., 1 + 1 = 2)
-	np.subtract	Subtraction (e.g., 3 - 2 = 1)
-	np.negative	Unary negation (e.g., -2)
*	np.multiply	Multiplication (e.g., 2 * 3 = 6)
/	np.divide	Division (e.g., 3 / 2 = 1.5)
//	np.floor_divide	Floor division (e.g., 3 // 2 = 1)
**np.power	Exponentiation (e.g., 2 ** 3 = 8)
%	np.mod	Modulus/remainder (e.g., 9 % 4 = 1)


In [ ]:
print(np.power(uarr,2))

[ 0  1  4  9 16 25 36 49 64 81]


In [ ]:
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)

array([5., 5., 2., 1.])

In [ ]:
x = [1, 2, 3]
print("x   =", x)
print("e^x =", np.exp(x))
print("2^x =", np.exp2(x))
print("3^x =", np.power(3., x))

x   = [1, 2, 3]
e^x = [ 2.71828183  7.3890561  20.08553692]
2^x = [2. 4. 8.]
3^x = [ 3.  9. 27.]


***Inverse Trigonometric Functions***

In [ ]:
x = [-1, 0, 1]
print("x         = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x         =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


***Trigonometric functions***

In [ ]:
x=[np.pi/3,20,0]
print("x         = ", x)
print("sin(x)    = ", np.sin(x))
print("cos(x)    = ", np.cos(x))
print("tan(x)    = ", np.tan(x))

x         =  [1.0471975511965976, 20, 0]
sin(x)    =  [0.8660254  0.91294525 0.        ]
cos(x)    =  [0.5        0.40808206 1.        ]
tan(x)    =  [1.73205081 2.23716094 0.        ]


***Logarithms***

In [ ]:
x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


The following table provides a list of useful aggregation functions available
in NumPy:

Function name	NaN-safe version	Description

np.sum	np.nansum	Compute sum of elements

np.prod	np.nanprod	Compute product of elements

np.mean	np.nanmean	Compute mean of elements

np.std	np.nanstd	Compute standard deviation

np.var	np.nanvar	Compute variance

np.min	np.nanmin	Find minimum value

np.max	np.nanmax	Find maximum value

np.argmin	np.nanargmin	Find index of minimum value

np.argmax	np.nanargmax	Find index of maximum value

np.median	np.nanmedian	Compute median of elements

np.percentile	np.nanpercentile	Compute rank-based statistics of elements

np.any	N/A	Evaluate whether any elements are true

np.all	N/A	Evaluate whether all elements are true




# ***Fancy Indexing***

In [ ]:
x=np.arange(15)
ind = [3, 7, 4]
x[ind]

array([3, 7, 4])

In [ ]:
[x[3], x[7], x[2]]

[3, 7, 2]

In [ ]:
X = np.arange(12).reshape((3, 4))
print(X)
row = np.array([0, 1, 2])
col = np.array([2, 1, 3])
X[row, col]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([ 2,  5, 11])

# ***Broadcasting***

In [ ]:
import numpy as np

arr = np.array([1, 2, 3])
result = arr + 10  # Scalar expands to [10, 10, 10]

print(result)


[11 12 13]


In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6]])  # Shape (2,3)
B = np.array([10, 20, 30])            # Shape (1,3) or (3,)

result = A + B  # B is broadcasted to match A
print(result)

[[11 22 33]
 [14 25 36]]


In [ ]:
row_vector = np.array([1, 2, 3])  # Shape (1,3)
col_vector = np.array([[10], [20], [30]])  # Shape (3,1)

result = row_vector + col_vector  # Broadcasts row_vector to (3,3)
print(result)


[[11 12 13]
 [21 22 23]
 [31 32 33]]


\[
\begin{array}{|c|c|c|c|}
\hline
\textbf{Operation} & \textbf{Array 1 Shape} & \textbf{Array 2 Shape} & \textbf{Resulting Shape} \\
\hline
\text{arr + 10} & (3,) & () \text{ (scalar)} & (3,) \\
\hline
A (2,3) + B (1,3) & (2,3) & (1,3) & (2,3) \\
\hline
\text{row\_vector (1,3) + col\_vector (3,1)} & (1,3) & (3,1) & (3,3) \\
\hline
\end{array}
\]


In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6]])  # Shape (2,3)
B = np.array([10, 20])  # Shape (2,)

result = A + B  # ERROR: Shapes are incompatible


ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

# **Sorting**

In [ ]:
import numpy as np
arr = np.array([3, 1, 2])
sorted_arr = np.sort(arr)
print(sorted_arr)  # Output: [1, 2, 3]


[1 2 3]


In [ ]:
indices = np.argsort(arr)
print(indices)  # Output: [1, 2, 0]


[1 2 0]


Partial Sorting

In [ ]:
k = 2
smallest_k = np.sort(arr)[:k]  # First 2 smallest elements
largest_k = np.sort(arr)[-k:]  # Last 2 largest elements
print(smallest_k)  # Output: [1, 2]
print(largest_k)   # Output: [2, 3]


[1 2]
[2 3]


# **Structured Arrays**

In [ ]:
data = np.array([(1, 'Alice', 85.5), (2, 'Bob', 92.0)],
                dtype=[('ID', 'i4'), ('Name', 'U10'), ('Score', 'f4')])
print(data['Name'])  # Access a specific field: ['Alice' 'Bob']


['Alice' 'Bob']


In [ ]:
import numpy as np

# Define a structured data type
data_type = [('ID', 'i4'), ('Name', 'U10'), ('Score', 'f4')]

# Create a structured array
students = np.array([(1, 'Alice', 85.5), (2, 'Bob', 92.0), (3, 'Charlie', 78.0)], dtype=data_type)

# Access data by field
print(students['Name'])   # Output: ['Alice' 'Bob' 'Charlie']
print(students['Score'])
print(students) # Output: [85.5 92.  78. ]


['Alice' 'Bob' 'Charlie']
[85.5 92.  78. ]
[(1, 'Alice', 85.5) (2, 'Bob', 92. ) (3, 'Charlie', 78. )]


In [ ]:
# Convert a structured array to a record array
record_students = students.view(np.recarray)

# Access using attribute-style
print(record_students.Name)  # Output: ['Alice' 'Bob' 'Charlie']
print(record_students.Score) # Output: [85.5 92.  78. ]


['Alice' 'Bob' 'Charlie']
[85.5 92.  78. ]


**Key Differences**
*   Structured Arrays: Access fields using keys like array
['field_name'].
*   Record Arrays: Allow access using both keys and attributes like recarray.field_name.

**Use Cases**

*Compound Types* : Useful for representing tabular data with
heterogenous types.

*Record Array*s: Convenient for quick access in research or testing when attribute-style access feels natural.